version: "3.7"
services:
  php:
    build: ./docker/php
    container_name: php
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    expose:
      - 9000
    volumes:
      - composer-cache:/root/composer/cache
      - .:/var/www/html
#      - type: volume
#        source: ./docker/php/conf/php.ini
#        target: /usr/local/etc/php/php.ini

  nginx:
    container_name: nginx
    depends_on:
      - php
    image: nginx:1.17.9-alpine
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
      - ./docker/nginx/conf/soundscape.conf:/etc/nginx/conf.d/soundscape.conf:ro

  mysql:
    image: mysql:8.0.19
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: soundscape
      MYSQL_USER: soundscape
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - mysql-cache:/db

volumes:
  composer-cache:
    driver: local
  mysql-cache:
    driver: local