version: "3.7"
services:
  php:
    build: ./docker/php
    container_name: php
    expose:
      - 9000
    volumes:
      - composer-cache:/root/composer/cache
      - .:/var/www/html
#      - type: volume
#        source: ./docker/php/conf/php.ini
#        target: /usr/local/etc/php/php.ini

  nginx:
    container_name: nginx
    depends_on:
      - php
    image: nginx:1.17.9-alpine
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
      - ./docker/nginx/conf/soundscape.conf:/etc/nginx/conf.d/soundscape.conf:ro

  db:
    build: ./docker/sqlite
    container_name: db
    stdin_open: true
    tty: true
    volumes:
      - db-cache:/db

volumes:
  composer-cache:
    driver: local
  db-cache:
    driver: local